//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkArchiveParser.Messages.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkArchiveParser.Messages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] category_messages {
            get {
                object obj = ResourceManager.GetObject("category:messages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] misc_generic_attachment {
            get {
                object obj = ResourceManager.GetObject("misc:generic_attachment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на body {
        ///	display: revert;
        ///    height: revert;
        ///}
        ///main {
        ///	display: flex;
        ///    flex-direction: column;
        ///}
        ///.peer_list * {
        ///	overflow: hidden;
        ///    white-space: nowrap;
        ///    text-overflow: ellipsis;
        ///}
        ///.peer_list {
        ///	margin: 1em;
        ///}
        ///.peer_list a {
        ///	display: grid;
        ///    grid-template-columns: auto 1fr auto;
        ///    grid-template-rows: 1fr 1fr;
        ///	align-items: center;
        ///}
        ///.im_peer_icon {
        ///	--mult: 24;
        ///	--div: calc(var(--mult) * var(--user-id1));
        ///    --floor: calc(var(--div) / 360 - .5);
        ///    --mod: calc(var(- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string style_messages {
            get {
                return ResourceManager.GetString("style:messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;user_id&quot;&gt;
        ///		&lt;meta name=&quot;category&quot; content=&quot;messages&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;darkar25&quot;&gt;
        ///		&lt;meta name=&quot;author_link&quot; content=&quot;https://vk.com/id305638772&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../index.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;messages.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;ul class=&quot;peer_list&quot;&gt;
        ///			
        ///		&lt;/ul&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string template_index_messages {
            get {
                return ResourceManager.GetString("template:index-messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;user_id&quot;&gt;
        ///		&lt;meta name=&quot;category&quot; content=&quot;messages&quot;&gt;
        ///		&lt;meta name=&quot;peer_id&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;darkar25&quot;&gt;
        ///		&lt;meta name=&quot;author_link&quot; content=&quot;https://vk.com/id305638772&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../../index.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../messages.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;header class=&quot;peer_header&quot;&gt;
        ///			&lt;a href=&quot;../index-messages.html&quot;&gt;&lt;img src=&quot;../../btn_left.svg&quot;/&gt;На [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string template_messages {
            get {
                return ResourceManager.GetString("template:messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;im_message_group&quot;&gt;
        ///	&lt;a id=&quot;im_user_icon&quot; class=&quot;rowspan2&quot;&gt;
        ///		&lt;div class=&quot;im_peer_icon rowspan2&quot;&gt;&lt;/div&gt;
        ///	&lt;/a&gt;
        ///	&lt;a id=&quot;message_title&quot;&gt;
        ///		&lt;strong id=&quot;user_name&quot;&gt;&lt;/strong&gt;
        ///	&lt;/a&gt;
        ///	&lt;a id=&quot;message_time&quot;&gt;
        ///		&lt;time&gt;&lt;/time&gt;
        ///	&lt;/a&gt;
        ///	&lt;ul id=&quot;messages&quot; class=&quot;colspan2&quot;&gt;
        ///		
        ///	&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string template_messages_message_group {
            get {
                return ResourceManager.GetString("template:messages-message-group", resourceCulture);
            }
        }
    }
}
