//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkArchiveParser.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkArchiveParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] category_unknown {
            get {
                object obj = ResourceManager.GetObject("category:unknown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] misc_btn_down {
            get {
                object obj = ResourceManager.GetObject("misc:btn_down", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] misc_btn_left {
            get {
                object obj = ResourceManager.GetObject("misc:btn_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] misc_favicon {
            get {
                object obj = ResourceManager.GetObject("misc:favicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @property --floor {
        ///	syntax: &apos;&lt;integer&gt;&apos;;
        ///	initial-value: 0;
        ///	inherits: false
        ///}
        ///@property --floor2 {
        ///	syntax: &apos;&lt;integer&gt;&apos;;
        ///	initial-value: 0;
        ///	inherits: false
        ///}
        ///@property --floor3 {
        ///	syntax: &apos;&lt;integer&gt;&apos;;
        ///	initial-value: 0;
        ///	inherits: false
        ///}
        ///@property --floor4 {
        ///	syntax: &apos;&lt;integer&gt;&apos;;
        ///	initial-value: 0;
        ///	inherits: false
        ///}
        ///
        ///body, html {
        ///	height: 100%
        ///}
        ///body {
        ///	margin: 0;
        ///	display: grid;
        ///    grid-template-rows: auto 1fr;
        ///}
        ///header {
        ///	border-bottom: solid 1px lightgray;
        ///    padding [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string style_index {
            get {
                return ResourceManager.GetString("style:index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;user_id&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;darkar25&quot;&gt;
        ///		&lt;meta name=&quot;author_link&quot; content=&quot;https://vk.com/id305638772&quot;&gt;
        ///		&lt;title&gt;VK Converted Archive&lt;/title&gt;
        ///		&lt;link rel=&quot;shortcut icon&quot; href=&quot;favicon.svg&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;index.css&quot;&gt;
        ///		&lt;base target=&quot;_root&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;header&gt;
        ///			&lt;div class=&quot;width headerwrapper&quot;&gt;
        ///				&lt;img src=&quot;favicon.svg&quot; alt=&quot;logo&quot;&gt;
        ///				&lt;strong&gt;ВКОНТАКТЕ&lt;/strong&gt;
        ///			&lt;/div&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string template_index {
            get {
                return ResourceManager.GetString("template:index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		Выберите категорию в левой части экрана.
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string template_placeholder {
            get {
                return ResourceManager.GetString("template:placeholder", resourceCulture);
            }
        }
    }
}
